rmsf<-read.csv("/home/ashraya/MD_Project/md_data_from_sneha/1LVA/rmsf_backbone_normalized.csv")
plot(rmsf$rmsf_norm,type="l",xlab="Residue Number",ylab="RMSF (in A)",col="red",main="1LVA backbone RMSF",xlim=c(1,258),ylim=c(0,1),xaxt='n')
axis(side=1, at=c(1,50,100,123,142,150,200,250),labels=T)
axis(side=1, at=c(1,53,100,123,154,200,250),labels=T)
par(mar=c(5,4,4,5)+.1)
variance<-read.csv("/home/ashraya/MD_Project/md_data_from_kalai/circular_var_nongly.csv")
variance<-read.csv("/home/ashraya/MD_Project/md_data_from_sneha/1LVA/1lva_phipsi_var_nongly.csv")
ggplot(variance,label=residue)+geom_point(aes(x=residue_number,y=var_phi),color="red")+geom_point(aes(x=residue_number,y=var_psi),color="blue")+xlab("Residue Number")+ylab("Variance")+geom_segment(aes(x=residue_number,xend=residue_number,y=0,yend=var_phi),alpha=0.5)+geom_segment(aes(x=residue_number,xend=residue_number,y=0,yend=var_psi),alpha=0.5)+geom_text(aes(x=residue_number,y=var_phi,label=ifelse(var_phi>0.1,as.character(paste(residue,residue_number,sep = ",")),'')),hjust=0,nudge_x = 0.5)+geom_text(aes(x=residue_number,y=var_psi,label=ifelse(var_psi>0.1,as.character(paste(residue,residue_number,sep = ",")),'')),hjust=0,nudge_x = 0.5)+theme(plot.margin=unit(c(1,3,0.5,0.5),"cm"))
+scale_color_manual(values=c("var_phi"="red","var_psi"="red"))
